/**
 * @file main.c
 * @author DFlubacher
 * @brief Template minimum example with CMake.
 * @version 0.1
 * @date 2022-04-26
 *
 *
 */

#include "main.h"

#include <stdint.h>

#include "bsp.h"
#include "printf-stdarg.h"
#include "stm32f303xe.h"

// Auto-generated by STM32CubeIDE with 'Targeted project': empty.
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning \
    "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 * @brief Bare metal programming template.
 * - Toggle LED with push-button press.
 * @return int
 */
int main(void) {
  uint8_t pb_state = 0;
  uint8_t pb_state_prev = 0;

  // Configure the System Clock.
  SystemClockConfig();

  // Initialize Console.
  BspConsoleInit();
  stm32_printf("\r\n\n------------------------\r\n");
  stm32_printf("Console initialized!\r\n");
  stm32_printf("SYSCLK: %d Hz\r\n", SystemCoreClock);
  stm32_printf("------------------------\r\n\n");

  // Initialize LED.
  BspLedInit();

  // Initialize push button.
  BspPbInit();

  /* Loop */
  for (;;) {
    pb_state = BspPbGetState();
    if (pb_state > 0 && pb_state_prev == 0) {
      BspLedToggle();
    }

    pb_state_prev = pb_state;
  }
}